sudo: required

language: python

services:
  - docker

before_install:
- docker-compose build
- docker-compose up -d

script:
- docker exec naas_api_1 python -m unittest discover
- docker exec naas_api_1 python -m unittest flake8

after_script:
- docker stop $(docker ps -a -q)
- docker rm $(docker ps -a -q)