version: '2'
services:
  db:
    image: postgres:9.5
    volumes:
      - /var/lib/postgresql/data
      - ./init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
      - PGDATA=/var/lib/postgresql/data   
  api:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=./NaaS/__init__.py
    links:
      - db:db
    ports:
      - "5000:5000"
    depends_on:
      - db
